import subprocess

from pydantic import BaseModel


# Fetch class executes the 'superfetch' command to retrieve data.
# It runs the command as a subprocess, captures the output, and handles errors.
# The class returns a list of output files generated by the 'superfetch' command.
class Fetch(BaseModel):
    def run(self, input_files: list[str], output_dir: str) -> list[str]:
        try:
            cmd = ["/tmp/superfetch", output_dir, *input_files]
            proc = subprocess.run(cmd, check=True, text=True, capture_output=True)
            return proc.stdout.splitlines()
        except subprocess.CalledProcessError as e:
            print(e.stderr)
            print(e.stdout)
            raise e
